### ISSUE TITLE
Running at 20MHz?

### ISSUE THREAD

**Issue by pjbulls** [kassu/KassutronicsQuantizer#6]
Hi kassu,

let me start off by saying thanks for the awesome quantizer, and making the design available to the community!

I was wondering whether it is possible to squeeze some extra performance out of the firmware by using a 20 MHz crystal instead of 16 MHz? I can imagine there's at least _some_ timing-sensitive things going on, but I guess the most important change would be that the PWM frequency (not duty cycle) would be slightly higher. Perhaps the shift registers would also run slightly faster?

Is this something you've already looked at or tried?

**Comment by kassu** [comment]
Hi! 

I have not tried running at 20MHz, but expect it would work fine without changes. As far as the code and PWM is concerned, everything scales with clock frequency so it will just run a bit faster.

The only thing to test separately is if the ADC performs as well. If I remember correctly, it is operating close to the maximum specified frequency. Running it faster won't break anything, but will reduce accuracy if the internal capacitances don't have time to charge up fully.

Feel free to try and report if it works!

**Comment by pjbulls** [comment]
Alright, thanks! I figured I'd ask first, since my design only really allows for 'destructive disassembly' (i.e. I probably cannot replace just the crystal).

You're right that ADC accuracy may be the biggest concern; I remember reading in several places that the ATMega328P's ADC can actually run reasonably well up to 1 MHz. I cannot find this rating in the datasheet which only mentions the 200 KHz limit, but see for example [here](https://electronics.stackexchange.com/questions/97606/analog-digital-conversion-clock-prescaling-atmega328p) for some discussion. With a prescaler of 64 and no need for full 10-bit accuracy it looks like it should be well within the limits.

I've gone ahead and plonked in a 20 MHz crystal. Calibration is done & everything seems to work as expected, so I'm going to call this a success! Thanks again for your input, and making available this amazing design 😄
